import { Destination, FlightOption } from "@/types";

const destinations: Record<string, Destination> = {
  paris: {
    slug: "paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    description:
      "The City of Light enchants visitors with its iconic landmarks, world-class museums, and charming café culture. From the Eiffel Tower to Montmartre, every corner tells a story.",
    bestMonths: ["April", "May", "June", "September", "October"],
    averageTemp: { high: 20, low: 10 },
    highlights: [
      "Eiffel Tower",
      "Louvre Museum",
      "Notre-Dame Cathedral",
      "Montmartre",
      "Seine River Cruise",
    ],
    imageUrl: "/destinations/paris.jpg",
    rating: 4.8,
    timezone: "Europe/Paris",
    favoriteFood: { name: "Croissant", description: "Flaky, buttery pastry that's a staple of every Parisian breakfast" },
    attractions: [
      { name: "Eiffel Tower", description: "Iconic iron lattice tower and symbol of Paris", imageUrl: "/attractions/eiffel-tower.jpg" },
      { name: "Louvre Museum", description: "World's largest art museum housing the Mona Lisa", imageUrl: "/attractions/louvre.jpg" },
      { name: "Sacré-Cœur Basilica", description: "White-domed basilica atop Montmartre hill", imageUrl: "/attractions/sacre-coeur.jpg" },
    ],
  },
  tokyo: {
    slug: "tokyo",
    name: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    description:
      "A mesmerizing blend of ultramodern and traditional, Tokyo dazzles with neon-lit skyscrapers, ancient temples, incredible food, and a culture that seamlessly bridges past and future.",
    bestMonths: ["March", "April", "May", "October", "November"],
    averageTemp: { high: 22, low: 12 },
    highlights: [
      "Shibuya Crossing",
      "Senso-ji Temple",
      "Tsukiji Fish Market",
      "Meiji Shrine",
      "Akihabara",
    ],
    imageUrl: "/destinations/tokyo.jpg",
    rating: 4.9,
    timezone: "Asia/Tokyo",
    favoriteFood: { name: "Ramen", description: "Rich, savory noodle soup with pork broth, chashu, and a soft-boiled egg" },
    attractions: [
      { name: "Senso-ji Temple", description: "Tokyo's oldest Buddhist temple in Asakusa", imageUrl: "/attractions/sensoji.jpg" },
      { name: "Shibuya Crossing", description: "World's busiest pedestrian crossing", imageUrl: "/attractions/shibuya.jpg" },
      { name: "Meiji Shrine", description: "Serene Shinto shrine surrounded by forest", imageUrl: "/attractions/meiji.jpg" },
    ],
  },
  bali: {
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    countryCode: "ID",
    description:
      "A tropical paradise known for its lush rice terraces, stunning temples, vibrant arts scene, and world-class surfing. Bali offers spiritual rejuvenation and adventure in equal measure.",
    bestMonths: ["April", "May", "June", "July", "August", "September"],
    averageTemp: { high: 30, low: 24 },
    highlights: [
      "Ubud Rice Terraces",
      "Uluwatu Temple",
      "Seminyak Beach",
      "Mount Batur Sunrise",
      "Tanah Lot",
    ],
    imageUrl: "/destinations/bali.jpg",
    rating: 4.7,
    timezone: "Asia/Makassar",
    favoriteFood: { name: "Nasi Goreng", description: "Fragrant Indonesian fried rice with sweet soy sauce, shrimp paste, and a fried egg" },
    attractions: [
      { name: "Tegallalang Rice Terraces", description: "Stunning terraced rice paddies in Ubud", imageUrl: "/attractions/tegallalang.jpg" },
      { name: "Uluwatu Temple", description: "Cliffside temple with ocean views and Kecak dance", imageUrl: "/attractions/uluwatu.jpg" },
      { name: "Tanah Lot", description: "Iconic sea temple perched on a rocky outcrop", imageUrl: "/attractions/tanah-lot.jpg" },
    ],
  },
  barcelona: {
    slug: "barcelona",
    name: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    description:
      "A vibrant Mediterranean gem where Gaudí's fantastical architecture meets golden beaches, incredible tapas, and an electric nightlife scene that pulses through winding Gothic streets.",
    bestMonths: ["May", "June", "September", "October"],
    averageTemp: { high: 24, low: 14 },
    highlights: [
      "Sagrada Familia",
      "Park Güell",
      "La Rambla",
      "Gothic Quarter",
      "Barceloneta Beach",
    ],
    imageUrl: "/destinations/barcelona.jpg",
    rating: 4.7,
    timezone: "Europe/Madrid",
    favoriteFood: { name: "Patatas Bravas", description: "Crispy fried potatoes drizzled with spicy tomato sauce and aioli" },
    attractions: [
      { name: "Sagrada Familia", description: "Gaudí's unfinished masterpiece basilica", imageUrl: "/attractions/sagrada-familia.jpg" },
      { name: "Park Güell", description: "Whimsical mosaic park designed by Gaudí", imageUrl: "/attractions/park-guell.jpg" },
      { name: "Gothic Quarter", description: "Medieval labyrinth of narrow streets and plazas", imageUrl: "/attractions/gothic-quarter.jpg" },
    ],
  },
  "new york": {
    slug: "new-york",
    name: "New York",
    country: "USA",
    countryCode: "US",
    description:
      "The city that never sleeps offers an unmatched energy with iconic skyline views, Broadway shows, diverse neighborhoods, world-class dining, and cultural institutions at every turn.",
    bestMonths: ["April", "May", "June", "September", "October", "November"],
    averageTemp: { high: 18, low: 8 },
    highlights: [
      "Central Park",
      "Statue of Liberty",
      "Times Square",
      "Brooklyn Bridge",
      "Metropolitan Museum",
    ],
    imageUrl: "/destinations/newyork.jpg",
    rating: 4.6,
    timezone: "America/New_York",
    favoriteFood: { name: "New York Pizza", description: "Thin-crust, foldable pizza slice with tangy tomato sauce and melted mozzarella" },
    attractions: [
      { name: "Statue of Liberty", description: "Iconic symbol of freedom on Liberty Island", imageUrl: "/attractions/statue-liberty.jpg" },
      { name: "Central Park", description: "843-acre urban oasis in Manhattan", imageUrl: "/attractions/central-park.jpg" },
      { name: "Empire State Building", description: "Art Deco skyscraper with panoramic observation deck", imageUrl: "/attractions/empire-state.jpg" },
    ],
  },
  london: {
    slug: "london",
    name: "London",
    country: "United Kingdom",
    countryCode: "GB",
    description:
      "A city steeped in history yet buzzing with contemporary culture. From Buckingham Palace to Borough Market, London offers royal grandeur alongside cutting-edge art and cuisine.",
    bestMonths: ["May", "June", "July", "August", "September"],
    averageTemp: { high: 18, low: 9 },
    highlights: [
      "Tower of London",
      "British Museum",
      "Buckingham Palace",
      "West End Theatre",
      "Hyde Park",
    ],
    imageUrl: "/destinations/london.jpg",
    rating: 4.7,
    timezone: "Europe/London",
    favoriteFood: { name: "Fish and Chips", description: "Golden battered cod with thick-cut chips, served with mushy peas and malt vinegar" },
    attractions: [
      { name: "Tower of London", description: "Historic castle and home of the Crown Jewels", imageUrl: "/attractions/tower-london.jpg" },
      { name: "British Museum", description: "World-renowned museum with free admission", imageUrl: "/attractions/british-museum.jpg" },
      { name: "Buckingham Palace", description: "Official London residence of the monarch", imageUrl: "/attractions/buckingham.jpg" },
    ],
  },
  rome: {
    slug: "rome",
    name: "Rome",
    country: "Italy",
    countryCode: "IT",
    description:
      "The Eternal City where ancient ruins stand alongside Renaissance masterpieces. Savor la dolce vita with incredible pasta, gelato, and espresso amid 3,000 years of history.",
    bestMonths: ["April", "May", "June", "September", "October"],
    averageTemp: { high: 24, low: 12 },
    highlights: [
      "Colosseum",
      "Vatican City",
      "Trevi Fountain",
      "Roman Forum",
      "Pantheon",
    ],
    imageUrl: "/destinations/rome.jpg",
    rating: 4.8,
    timezone: "Europe/Rome",
    favoriteFood: { name: "Cacio e Pepe", description: "Classic Roman pasta with pecorino cheese and black pepper in a creamy sauce" },
    attractions: [
      { name: "Colosseum", description: "Iconic ancient amphitheater of gladiatorial contests", imageUrl: "/attractions/colosseum.jpg" },
      { name: "Vatican Museums", description: "Vast art collection including the Sistine Chapel", imageUrl: "/attractions/vatican.jpg" },
      { name: "Trevi Fountain", description: "Baroque masterpiece where visitors toss coins for luck", imageUrl: "/attractions/trevi.jpg" },
    ],
  },
  dubai: {
    slug: "dubai",
    name: "Dubai",
    country: "UAE",
    countryCode: "AE",
    description:
      "A futuristic oasis of luxury rising from the desert. Dubai dazzles with record-breaking architecture, lavish shopping malls, golden beaches, and an ever-evolving skyline.",
    bestMonths: [
      "November",
      "December",
      "January",
      "February",
      "March",
    ],
    averageTemp: { high: 32, low: 20 },
    highlights: [
      "Burj Khalifa",
      "Dubai Mall",
      "Palm Jumeirah",
      "Desert Safari",
      "Dubai Marina",
    ],
    imageUrl: "/destinations/dubai.jpg",
    rating: 4.6,
    timezone: "Asia/Dubai",
    favoriteFood: { name: "Shawarma", description: "Juicy spiced meat wrapped in warm flatbread with garlic sauce and pickles" },
    attractions: [
      { name: "Burj Khalifa", description: "World's tallest building with observation decks", imageUrl: "/attractions/burj-khalifa.jpg" },
      { name: "Palm Jumeirah", description: "Iconic palm-shaped artificial island", imageUrl: "/attractions/palm-jumeirah.jpg" },
      { name: "Dubai Mall", description: "One of the world's largest shopping destinations", imageUrl: "/attractions/dubai-mall.jpg" },
    ],
  },
  sydney: {
    slug: "sydney",
    name: "Sydney",
    country: "Australia",
    countryCode: "AU",
    description:
      "A stunning harbor city where golden beaches meet cosmopolitan culture. Iconic landmarks, world-class dining, and year-round outdoor adventures make Sydney truly unforgettable.",
    bestMonths: ["September", "October", "November", "March", "April", "May"],
    averageTemp: { high: 24, low: 16 },
    highlights: [
      "Sydney Opera House",
      "Harbour Bridge",
      "Bondi Beach",
      "Darling Harbour",
      "Blue Mountains",
    ],
    imageUrl: "/destinations/sydney.jpg",
    rating: 4.7,
    timezone: "Australia/Sydney",
    favoriteFood: { name: "Meat Pie", description: "Flaky pastry filled with seasoned minced beef and rich gravy" },
    attractions: [
      { name: "Sydney Opera House", description: "Architectural masterpiece on the harbour", imageUrl: "/attractions/opera-house.jpg" },
      { name: "Harbour Bridge", description: "Iconic bridge with a famous climb experience", imageUrl: "/attractions/harbour-bridge.jpg" },
      { name: "Bondi Beach", description: "World-famous surf beach with coastal walks", imageUrl: "/attractions/bondi.jpg" },
    ],
  },
  "machu picchu": {
    slug: "machu-picchu",
    name: "Machu Picchu",
    country: "Peru",
    countryCode: "PE",
    description:
      "The Lost City of the Incas perched high in the Andes. This breathtaking archaeological wonder offers a profound connection to ancient civilization amid dramatic mountain scenery.",
    bestMonths: ["April", "May", "September", "October"],
    averageTemp: { high: 20, low: 8 },
    highlights: [
      "Inca Trail",
      "Sun Gate",
      "Temple of the Sun",
      "Huayna Picchu",
      "Sacred Valley",
    ],
    imageUrl: "/destinations/machupicchu.jpg",
    rating: 4.9,
    timezone: "America/Lima",
    favoriteFood: { name: "Lomo Saltado", description: "Peruvian stir-fry of beef, tomatoes, and onions served over rice and fries" },
    attractions: [
      { name: "Inca Trail", description: "Legendary multi-day trek to the citadel", imageUrl: "/attractions/inca-trail.jpg" },
      { name: "Huayna Picchu", description: "Steep peak with panoramic ruins views", imageUrl: "/attractions/huayna-picchu.jpg" },
      { name: "Temple of the Sun", description: "Sacred Inca temple with astronomical alignment", imageUrl: "/attractions/temple-sun.jpg" },
    ],
  },
  santorini: {
    slug: "santorini",
    name: "Santorini",
    country: "Greece",
    countryCode: "GR",
    description:
      "A breathtaking volcanic island with iconic white-washed buildings and blue domes perched on dramatic cliffs overlooking the azure Aegean Sea. Famous for spectacular sunsets.",
    bestMonths: ["May", "June", "September", "October"],
    averageTemp: { high: 26, low: 18 },
    highlights: [
      "Oia Sunset",
      "Red Beach",
      "Fira Town",
      "Akrotiri Ruins",
      "Wine Tasting",
    ],
    imageUrl: "/destinations/santorini.jpg",
    rating: 4.8,
    timezone: "Europe/Athens",
    favoriteFood: { name: "Gyros", description: "Warm pita stuffed with seasoned meat, tzatziki, tomatoes, and onions" },
    attractions: [
      { name: "Oia Village", description: "Picturesque village famous for stunning sunsets", imageUrl: "/attractions/oia.jpg" },
      { name: "Red Beach", description: "Dramatic volcanic beach with crimson cliffs", imageUrl: "/attractions/red-beach.jpg" },
      { name: "Akrotiri", description: "Preserved Minoan Bronze Age settlement", imageUrl: "/attractions/akrotiri.jpg" },
    ],
  },
  maldives: {
    slug: "maldives",
    name: "Maldives",
    country: "Maldives",
    countryCode: "MV",
    description:
      "A tropical paradise of crystal-clear turquoise waters, pristine white-sand beaches, and luxury overwater villas. The ultimate destination for diving, relaxation, and romance.",
    bestMonths: [
      "November",
      "December",
      "January",
      "February",
      "March",
      "April",
    ],
    averageTemp: { high: 31, low: 26 },
    highlights: [
      "Overwater Villas",
      "Snorkeling & Diving",
      "Bioluminescent Beach",
      "Whale Shark Spotting",
      "Underwater Restaurant",
    ],
    imageUrl: "/destinations/maldives.jpg",
    rating: 4.9,
    timezone: "Indian/Maldives",
    favoriteFood: { name: "Mas Huni", description: "Traditional Maldivian breakfast of shredded smoked tuna, coconut, and onion with flatbread" },
    attractions: [
      { name: "Bioluminescent Beach", description: "Glowing plankton illuminating the shore at night", imageUrl: "/attractions/bio-beach.jpg" },
      { name: "Banana Reef", description: "One of the Maldives' first dive sites", imageUrl: "/attractions/banana-reef.jpg" },
      { name: "Ithaa Undersea Restaurant", description: "All-glass underwater dining experience", imageUrl: "/attractions/ithaa.jpg" },
    ],
  },
  amsterdam: {
    slug: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    description:
      "A charming city of canal rings, cycling culture, and world-class art museums. Amsterdam blends a rich Golden Age heritage with progressive modern energy.",
    bestMonths: ["April", "May", "June", "September"],
    averageTemp: { high: 17, low: 8 },
    highlights: ["Canal Cruises", "Rijksmuseum", "Anne Frank House", "Vondelpark", "Jordaan District"],
    imageUrl: "/destinations/amsterdam.jpg",
    rating: 4.6,
    timezone: "Europe/Amsterdam",
    favoriteFood: { name: "Stroopwafel", description: "Thin, warm waffle cookie filled with caramel syrup, best enjoyed fresh from a street vendor" },
    attractions: [
      { name: "Rijksmuseum", description: "Dutch national museum featuring Rembrandt and Vermeer", imageUrl: "/attractions/rijksmuseum.jpg" },
      { name: "Anne Frank House", description: "Moving WWII memorial museum in a hidden annex", imageUrl: "/attractions/anne-frank.jpg" },
      { name: "Van Gogh Museum", description: "World's largest collection of Van Gogh's works", imageUrl: "/attractions/van-gogh.jpg" },
    ],
  },
  bangkok: {
    slug: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    description:
      "A vibrant capital where ornate temples rise alongside gleaming skyscrapers. Bangkok enthralls with its legendary street food, floating markets, and exuberant nightlife.",
    bestMonths: ["November", "December", "January", "February"],
    averageTemp: { high: 34, low: 26 },
    highlights: ["Grand Palace", "Wat Arun", "Chatuchak Market", "Khao San Road", "Floating Markets"],
    imageUrl: "/destinations/bangkok.jpg",
    rating: 4.5,
    timezone: "Asia/Bangkok",
    favoriteFood: { name: "Pad Thai", description: "Stir-fried rice noodles with shrimp, tofu, peanuts, bean sprouts, and tamarind sauce" },
    attractions: [
      { name: "Grand Palace", description: "Dazzling former royal residence with Emerald Buddha", imageUrl: "/attractions/grand-palace.jpg" },
      { name: "Wat Arun", description: "Temple of Dawn with striking porcelain-tiled spire", imageUrl: "/attractions/wat-arun.jpg" },
      { name: "Chatuchak Market", description: "One of the world's largest weekend markets", imageUrl: "/attractions/chatuchak.jpg" },
    ],
  },
  "cape town": {
    slug: "cape-town",
    name: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    description:
      "A breathtaking city nestled between Table Mountain and the Atlantic Ocean. Cape Town offers dramatic landscapes, vibrant culture, world-class wine, and incredible biodiversity.",
    bestMonths: ["October", "November", "December", "January", "February", "March"],
    averageTemp: { high: 25, low: 15 },
    highlights: ["Table Mountain", "Cape of Good Hope", "Robben Island", "V&A Waterfront", "Winelands"],
    imageUrl: "/destinations/capetown.jpg",
    rating: 4.7,
    timezone: "Africa/Johannesburg",
    favoriteFood: { name: "Bobotie", description: "Cape Malay spiced minced meat bake topped with a savory egg custard" },
    attractions: [
      { name: "Table Mountain", description: "Flat-topped mountain with cable car and hiking trails", imageUrl: "/attractions/table-mountain.jpg" },
      { name: "Cape of Good Hope", description: "Dramatic headland at the southwestern tip of Africa", imageUrl: "/attractions/cape-hope.jpg" },
      { name: "Robben Island", description: "Historic island prison where Mandela was held", imageUrl: "/attractions/robben-island.jpg" },
    ],
  },
  marrakech: {
    slug: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    countryCode: "MA",
    description:
      "An intoxicating city of spice-scented souks, ornate palaces, and the bustling Jemaa el-Fnaa square. Marrakech immerses visitors in a sensory feast of color, sound, and flavor.",
    bestMonths: ["March", "April", "May", "October", "November"],
    averageTemp: { high: 28, low: 14 },
    highlights: ["Jemaa el-Fnaa", "Majorelle Garden", "Bahia Palace", "Medina Souks", "Atlas Mountains"],
    imageUrl: "/destinations/marrakech.jpg",
    rating: 4.5,
    timezone: "Africa/Casablanca",
    favoriteFood: { name: "Tagine", description: "Slow-cooked stew of tender meat, preserved lemons, and olives in an earthenware pot" },
    attractions: [
      { name: "Jemaa el-Fnaa", description: "Legendary square with performers, food stalls, and snake charmers", imageUrl: "/attractions/jemaa.jpg" },
      { name: "Majorelle Garden", description: "Stunning botanical garden with cobalt blue accents", imageUrl: "/attractions/majorelle.jpg" },
      { name: "Bahia Palace", description: "19th-century palace with intricate tilework and gardens", imageUrl: "/attractions/bahia.jpg" },
    ],
  },
  prague: {
    slug: "prague",
    name: "Prague",
    country: "Czech Republic",
    countryCode: "CZ",
    description:
      "The City of a Hundred Spires enchants with its fairy-tale Old Town, Gothic cathedrals, and lively beer culture. Prague is one of Europe's most photogenic and affordable capitals.",
    bestMonths: ["April", "May", "June", "September", "October"],
    averageTemp: { high: 19, low: 8 },
    highlights: ["Charles Bridge", "Prague Castle", "Old Town Square", "Astronomical Clock", "Petřín Hill"],
    imageUrl: "/destinations/prague.jpg",
    rating: 4.6,
    timezone: "Europe/Prague",
    favoriteFood: { name: "Trdelník", description: "Warm, sugar-coated rolled pastry grilled over charcoal, often filled with ice cream" },
    attractions: [
      { name: "Prague Castle", description: "Largest ancient castle complex in the world", imageUrl: "/attractions/prague-castle.jpg" },
      { name: "Charles Bridge", description: "Iconic 14th-century stone bridge lined with statues", imageUrl: "/attractions/charles-bridge.jpg" },
      { name: "Astronomical Clock", description: "Medieval clock with hourly show of moving apostles", imageUrl: "/attractions/astro-clock.jpg" },
    ],
  },
  istanbul: {
    slug: "istanbul",
    name: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    description:
      "A transcontinental metropolis straddling Europe and Asia. Istanbul dazzles with its Byzantine and Ottoman heritage, bustling bazaars, and a culinary scene that bridges two worlds.",
    bestMonths: ["April", "May", "September", "October"],
    averageTemp: { high: 22, low: 12 },
    highlights: ["Hagia Sophia", "Blue Mosque", "Grand Bazaar", "Bosphorus Cruise", "Topkapi Palace"],
    imageUrl: "/destinations/istanbul.jpg",
    rating: 4.7,
    timezone: "Europe/Istanbul",
    favoriteFood: { name: "Kebab", description: "Succulent grilled meat served with warm flatbread, fresh salad, and tangy sumac onions" },
    attractions: [
      { name: "Hagia Sophia", description: "Awe-inspiring 6th-century cathedral turned mosque", imageUrl: "/attractions/hagia-sophia.jpg" },
      { name: "Grand Bazaar", description: "One of the world's oldest and largest covered markets", imageUrl: "/attractions/grand-bazaar.jpg" },
      { name: "Topkapi Palace", description: "Opulent Ottoman palace with stunning Bosphorus views", imageUrl: "/attractions/topkapi.jpg" },
    ],
  },
  "rio de janeiro": {
    slug: "rio-de-janeiro",
    name: "Rio de Janeiro",
    country: "Brazil",
    countryCode: "BR",
    description:
      "A vibrant city of samba rhythms, golden beaches, and dramatic mountain scenery. Rio pulses with carnival energy, from Copacabana's shores to Sugarloaf Mountain's summit.",
    bestMonths: ["May", "June", "July", "August", "September"],
    averageTemp: { high: 28, low: 22 },
    highlights: ["Christ the Redeemer", "Copacabana Beach", "Sugarloaf Mountain", "Carnival", "Tijuca Forest"],
    imageUrl: "/destinations/rio.jpg",
    rating: 4.6,
    timezone: "America/Sao_Paulo",
    favoriteFood: { name: "Feijoada", description: "Hearty black bean stew with pork, served with rice, collard greens, and orange slices" },
    attractions: [
      { name: "Christ the Redeemer", description: "Iconic Art Deco statue atop Corcovado mountain", imageUrl: "/attractions/christ-redeemer.jpg" },
      { name: "Sugarloaf Mountain", description: "Cable car ride to a peak with sweeping bay views", imageUrl: "/attractions/sugarloaf.jpg" },
      { name: "Copacabana Beach", description: "World-famous crescent beach with lively boardwalk", imageUrl: "/attractions/copacabana.jpg" },
    ],
  },
  singapore: {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    description:
      "A gleaming city-state where futuristic gardens meet hawker stall feasts. Singapore is a melting pot of Malay, Chinese, and Indian cultures wrapped in tropical greenery.",
    bestMonths: ["February", "March", "April", "October", "November"],
    averageTemp: { high: 31, low: 25 },
    highlights: ["Gardens by the Bay", "Marina Bay Sands", "Chinatown", "Sentosa Island", "Hawker Centres"],
    imageUrl: "/destinations/singapore.jpg",
    rating: 4.7,
    timezone: "Asia/Singapore",
    favoriteFood: { name: "Hainanese Chicken Rice", description: "Tender poached chicken over fragrant rice with chili and ginger sauces" },
    attractions: [
      { name: "Gardens by the Bay", description: "Futuristic park with towering Supertree structures", imageUrl: "/attractions/gardens-bay.jpg" },
      { name: "Marina Bay Sands", description: "Iconic hotel with infinity pool and SkyPark", imageUrl: "/attractions/marina-bay.jpg" },
      { name: "Hawker Centres", description: "Affordable open-air food courts with local delicacies", imageUrl: "/attractions/hawker.jpg" },
    ],
  },
  "buenos aires": {
    slug: "buenos-aires",
    name: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    description:
      "The Paris of South America pulsates with tango, sizzling steakhouses, and European-inspired architecture. Buenos Aires is a cultural powerhouse brimming with passion.",
    bestMonths: ["March", "April", "May", "October", "November"],
    averageTemp: { high: 24, low: 14 },
    highlights: ["La Boca", "Recoleta Cemetery", "San Telmo Market", "Tango Shows", "Puerto Madero"],
    imageUrl: "/destinations/buenosaires.jpg",
    rating: 4.5,
    timezone: "America/Argentina/Buenos_Aires",
    favoriteFood: { name: "Asado", description: "Traditional Argentine barbecue of slow-grilled beef ribs and chorizo with chimichurri" },
    attractions: [
      { name: "La Boca", description: "Colorful neighborhood famed for tango and street art", imageUrl: "/attractions/la-boca.jpg" },
      { name: "Recoleta Cemetery", description: "Ornate cemetery with elaborate mausoleums", imageUrl: "/attractions/recoleta.jpg" },
      { name: "Teatro Colón", description: "One of the world's finest opera houses", imageUrl: "/attractions/teatro-colon.jpg" },
    ],
  },
  kyoto: {
    slug: "kyoto",
    name: "Kyoto",
    country: "Japan",
    countryCode: "JP",
    description:
      "Japan's cultural heart, where thousands of temples, serene bamboo groves, and exquisite kaiseki cuisine preserve centuries of tradition amid stunning natural beauty.",
    bestMonths: ["March", "April", "May", "October", "November"],
    averageTemp: { high: 21, low: 10 },
    highlights: ["Fushimi Inari Shrine", "Arashiyama Bamboo Grove", "Kinkaku-ji", "Geisha District", "Tea Ceremonies"],
    imageUrl: "/destinations/kyoto.jpg",
    rating: 4.9,
    timezone: "Asia/Tokyo",
    favoriteFood: { name: "Kaiseki", description: "Exquisite multi-course meal showcasing seasonal ingredients with artful presentation" },
    attractions: [
      { name: "Fushimi Inari Shrine", description: "Thousands of vermillion torii gates on a mountain trail", imageUrl: "/attractions/fushimi-inari.jpg" },
      { name: "Kinkaku-ji", description: "Stunning golden pavilion reflected in a mirror pond", imageUrl: "/attractions/kinkakuji.jpg" },
      { name: "Arashiyama Bamboo Grove", description: "Ethereal pathway through towering bamboo stalks", imageUrl: "/attractions/arashiyama.jpg" },
    ],
  },
  lisbon: {
    slug: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    description:
      "A sun-drenched hillside capital with vintage trams, pastel-colored buildings, and legendary custard tarts. Lisbon blends old-world charm with a vibrant contemporary arts scene.",
    bestMonths: ["April", "May", "June", "September", "October"],
    averageTemp: { high: 23, low: 13 },
    highlights: ["Belém Tower", "Alfama District", "Tram 28", "Jerónimos Monastery", "Pastéis de Belém"],
    imageUrl: "/destinations/lisbon.jpg",
    rating: 4.6,
    timezone: "Europe/Lisbon",
    favoriteFood: { name: "Pastel de Nata", description: "Crispy custard tart with a caramelized top, dusted with cinnamon and powdered sugar" },
    attractions: [
      { name: "Belém Tower", description: "16th-century fortified tower on the Tagus River", imageUrl: "/attractions/belem-tower.jpg" },
      { name: "Alfama District", description: "Oldest neighborhood with Fado music and narrow alleys", imageUrl: "/attractions/alfama.jpg" },
      { name: "Jerónimos Monastery", description: "Ornate Manueline-style monastery and UNESCO site", imageUrl: "/attractions/jeronimos.jpg" },
    ],
  },
  vienna: {
    slug: "vienna",
    name: "Vienna",
    country: "Austria",
    countryCode: "AT",
    description:
      "An imperial city of grand palaces, classical music, and sublime coffee house culture. Vienna combines Habsburg elegance with cutting-edge contemporary design.",
    bestMonths: ["April", "May", "June", "September", "October"],
    averageTemp: { high: 20, low: 9 },
    highlights: ["Schönbrunn Palace", "St. Stephen's Cathedral", "Belvedere Museum", "Vienna State Opera", "Naschmarkt"],
    imageUrl: "/destinations/vienna.jpg",
    rating: 4.7,
    timezone: "Europe/Vienna",
    favoriteFood: { name: "Wiener Schnitzel", description: "Golden, crispy breaded veal cutlet served with a wedge of lemon and potato salad" },
    attractions: [
      { name: "Schönbrunn Palace", description: "Former imperial summer residence with vast gardens", imageUrl: "/attractions/schonbrunn.jpg" },
      { name: "St. Stephen's Cathedral", description: "Gothic cathedral dominating the city's skyline", imageUrl: "/attractions/st-stephens.jpg" },
      { name: "Belvedere Museum", description: "Baroque palace housing Klimt's The Kiss", imageUrl: "/attractions/belvedere.jpg" },
    ],
  },
  "hong kong": {
    slug: "hong-kong",
    name: "Hong Kong",
    country: "China",
    countryCode: "CN",
    description:
      "A dazzling skyline meets ancient traditions in this dynamic metropolis. Hong Kong thrills with dim sum feasts, harbor views, hiking trails, and a relentless urban energy.",
    bestMonths: ["October", "November", "December"],
    averageTemp: { high: 27, low: 21 },
    highlights: ["Victoria Peak", "Star Ferry", "Temple Street Market", "Big Buddha", "Lan Kwai Fong"],
    imageUrl: "/destinations/hongkong.jpg",
    rating: 4.6,
    timezone: "Asia/Hong_Kong",
    favoriteFood: { name: "Dim Sum", description: "Steamed dumplings, buns, and small bites served from bamboo baskets with tea" },
    attractions: [
      { name: "Victoria Peak", description: "Mountain summit with panoramic skyline views", imageUrl: "/attractions/victoria-peak.jpg" },
      { name: "Big Buddha", description: "Massive bronze seated Buddha statue on Lantau Island", imageUrl: "/attractions/big-buddha.jpg" },
      { name: "Star Ferry", description: "Legendary harbour crossing with stunning views", imageUrl: "/attractions/star-ferry.jpg" },
    ],
  },
  cusco: {
    slug: "cusco",
    name: "Cusco",
    country: "Peru",
    countryCode: "PE",
    description:
      "The former capital of the Inca Empire, Cusco captivates with its blend of Inca stonework and Spanish colonial architecture set high in the Peruvian Andes.",
    bestMonths: ["May", "June", "July", "August", "September"],
    averageTemp: { high: 19, low: 2 },
    highlights: ["Plaza de Armas", "Sacsayhuamán", "San Pedro Market", "Rainbow Mountain", "Sacred Valley"],
    imageUrl: "/destinations/cusco.jpg",
    rating: 4.7,
    timezone: "America/Lima",
    favoriteFood: { name: "Cuy al Horno", description: "Roasted guinea pig, a traditional Andean delicacy served whole with potatoes" },
    attractions: [
      { name: "Sacsayhuamán", description: "Massive Inca fortress with perfectly fitted stones", imageUrl: "/attractions/sacsayhuaman.jpg" },
      { name: "Plaza de Armas", description: "Grand central square surrounded by colonial arcades", imageUrl: "/attractions/plaza-armas.jpg" },
      { name: "Rainbow Mountain", description: "Colorful striped mountain at 5,200m elevation", imageUrl: "/attractions/rainbow-mountain.jpg" },
    ],
  },
  cairo: {
    slug: "cairo",
    name: "Cairo",
    country: "Egypt",
    countryCode: "EG",
    description:
      "A chaotic, captivating megalopolis where the ancient pyramids of Giza stand watch over a teeming modern city. Cairo is the gateway to pharaonic wonders and Nile cruises.",
    bestMonths: ["October", "November", "December", "January", "February", "March"],
    averageTemp: { high: 30, low: 16 },
    highlights: ["Pyramids of Giza", "Egyptian Museum", "Khan el-Khalili", "Nile River Cruise", "Sphinx"],
    imageUrl: "/destinations/cairo.jpg",
    rating: 4.5,
    timezone: "Africa/Cairo",
    favoriteFood: { name: "Koshari", description: "Egypt's national dish of rice, lentils, and pasta topped with spiced tomato sauce and crispy onions" },
    attractions: [
      { name: "Pyramids of Giza", description: "Last surviving wonder of the ancient world", imageUrl: "/attractions/pyramids.jpg" },
      { name: "Egyptian Museum", description: "Vast collection including Tutankhamun's treasures", imageUrl: "/attractions/egyptian-museum.jpg" },
      { name: "Khan el-Khalili", description: "Historic bazaar dating back to the 14th century", imageUrl: "/attractions/khan-khalili.jpg" },
    ],
  },
  reykjavik: {
    slug: "reykjavik",
    name: "Reykjavik",
    country: "Iceland",
    countryCode: "IS",
    description:
      "The world's northernmost capital, a gateway to glaciers, geysers, and the Northern Lights. Reykjavik pairs raw natural beauty with colorful streets and creative culture.",
    bestMonths: ["June", "July", "August"],
    averageTemp: { high: 13, low: 4 },
    highlights: ["Northern Lights", "Blue Lagoon", "Golden Circle", "Hallgrímskirkja", "Whale Watching"],
    imageUrl: "/destinations/reykjavik.jpg",
    rating: 4.7,
    timezone: "Atlantic/Reykjavik",
    favoriteFood: { name: "Lamb Soup", description: "Hearty Icelandic lamb stew with root vegetables and fresh herbs" },
    attractions: [
      { name: "Blue Lagoon", description: "Geothermal spa with milky blue mineral-rich waters", imageUrl: "/attractions/blue-lagoon.jpg" },
      { name: "Hallgrímskirkja", description: "Striking church inspired by basalt column formations", imageUrl: "/attractions/hallgrimskirkja.jpg" },
      { name: "Golden Circle", description: "Route linking geysers, waterfalls, and tectonic plates", imageUrl: "/attractions/golden-circle.jpg" },
    ],
  },
  "kuala lumpur": {
    slug: "kuala-lumpur",
    name: "Kuala Lumpur",
    country: "Malaysia",
    countryCode: "MY",
    description:
      "A multicultural capital where gleaming skyscrapers tower above colonial-era buildings, bustling hawker stalls, and ornate mosques. KL is Southeast Asia's most diverse city.",
    bestMonths: ["January", "February", "June", "July", "August"],
    averageTemp: { high: 33, low: 24 },
    highlights: ["Petronas Towers", "Batu Caves", "Jalan Alor Food Street", "KL Tower", "Merdeka Square"],
    imageUrl: "/destinations/kualalumpur.jpg",
    rating: 4.4,
    timezone: "Asia/Kuala_Lumpur",
    favoriteFood: { name: "Nasi Lemak", description: "Fragrant coconut rice with sambal, anchovies, peanuts, and a boiled egg" },
    attractions: [
      { name: "Petronas Twin Towers", description: "Iconic 88-storey twin skyscrapers with skybridge", imageUrl: "/attractions/petronas.jpg" },
      { name: "Batu Caves", description: "Limestone caves with a towering Hindu shrine", imageUrl: "/attractions/batu-caves.jpg" },
      { name: "Jalan Alor", description: "Vibrant night food street with Southeast Asian flavors", imageUrl: "/attractions/jalan-alor.jpg" },
    ],
  },
  hanoi: {
    slug: "hanoi",
    name: "Hanoi",
    country: "Vietnam",
    countryCode: "VN",
    description:
      "Vietnam's captivating capital where French colonial elegance meets ancient Vietnamese culture. Hanoi charms with its Old Quarter, street food, and serene lakes.",
    bestMonths: ["October", "November", "March", "April"],
    averageTemp: { high: 28, low: 20 },
    highlights: ["Hoan Kiem Lake", "Old Quarter", "Ho Chi Minh Mausoleum", "Temple of Literature", "Street Food Tours"],
    imageUrl: "/destinations/hanoi.jpg",
    rating: 4.5,
    timezone: "Asia/Ho_Chi_Minh",
    favoriteFood: { name: "Pho", description: "Aromatic beef or chicken noodle soup with fresh herbs, bean sprouts, and lime" },
    attractions: [
      { name: "Hoan Kiem Lake", description: "Scenic lake with the iconic red Huc Bridge", imageUrl: "/attractions/hoan-kiem.jpg" },
      { name: "Temple of Literature", description: "Vietnam's first university dating to 1070", imageUrl: "/attractions/temple-literature.jpg" },
      { name: "Old Quarter", description: "Ancient trading district with 36 bustling streets", imageUrl: "/attractions/old-quarter.jpg" },
    ],
  },
  "san francisco": {
    slug: "san-francisco",
    name: "San Francisco",
    country: "USA",
    countryCode: "US",
    description:
      "A hilly, fog-kissed city of iconic bridges, Victorian painted ladies, and pioneering tech culture. San Francisco enchants with its diverse neighborhoods and stunning bay views.",
    bestMonths: ["September", "October", "April", "May"],
    averageTemp: { high: 18, low: 11 },
    highlights: ["Golden Gate Bridge", "Alcatraz Island", "Fisherman's Wharf", "Chinatown", "Cable Cars"],
    imageUrl: "/destinations/sanfrancisco.jpg",
    rating: 4.6,
    timezone: "America/Los_Angeles",
    favoriteFood: { name: "Clam Chowder in Bread Bowl", description: "Creamy New England clam chowder served in a hollowed-out sourdough bread bowl" },
    attractions: [
      { name: "Golden Gate Bridge", description: "Iconic orange suspension bridge spanning the bay", imageUrl: "/attractions/golden-gate.jpg" },
      { name: "Alcatraz Island", description: "Notorious former federal prison on a bay island", imageUrl: "/attractions/alcatraz.jpg" },
      { name: "Fisherman's Wharf", description: "Waterfront district with seafood and sea lions", imageUrl: "/attractions/fishermans-wharf.jpg" },
    ],
  },
  athens: {
    slug: "athens",
    name: "Athens",
    country: "Greece",
    countryCode: "GR",
    description:
      "The cradle of Western civilization, where the Acropolis presides over a vibrant modern city. Athens offers ancient ruins, lively tavernas, and warm Mediterranean hospitality.",
    bestMonths: ["April", "May", "June", "September", "October"],
    averageTemp: { high: 26, low: 15 },
    highlights: ["Acropolis", "Plaka District", "National Archaeological Museum", "Temple of Zeus", "Monastiraki Flea Market"],
    imageUrl: "/destinations/athens.jpg",
    rating: 4.6,
    timezone: "Europe/Athens",
    favoriteFood: { name: "Souvlaki", description: "Grilled meat skewers served in pita with tzatziki, tomatoes, and crispy fries" },
    attractions: [
      { name: "Acropolis", description: "Ancient citadel with the iconic Parthenon temple", imageUrl: "/attractions/acropolis.jpg" },
      { name: "Plaka District", description: "Charming old neighborhood at the foot of the Acropolis", imageUrl: "/attractions/plaka.jpg" },
      { name: "Temple of Olympian Zeus", description: "Ruins of a colossal temple dedicated to Zeus", imageUrl: "/attractions/temple-zeus.jpg" },
    ],
  },
  "mexico city": {
    slug: "mexico-city",
    name: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    description:
      "A sprawling, vibrant capital built on the ruins of the Aztec empire. Mexico City astounds with world-class museums, incredible street food, and a deep cultural soul.",
    bestMonths: ["March", "April", "May", "October", "November"],
    averageTemp: { high: 24, low: 12 },
    highlights: ["Zócalo", "Frida Kahlo Museum", "Teotihuacán", "Chapultepec Castle", "Coyoacán"],
    imageUrl: "/destinations/mexicocity.jpg",
    rating: 4.5,
    timezone: "America/Mexico_City",
    favoriteFood: { name: "Tacos al Pastor", description: "Spit-roasted pork tacos with pineapple, cilantro, and onion on corn tortillas" },
    attractions: [
      { name: "Teotihuacán", description: "Massive ancient pyramids of the Sun and Moon", imageUrl: "/attractions/teotihuacan.jpg" },
      { name: "Frida Kahlo Museum", description: "Artist's iconic Blue House turned museum", imageUrl: "/attractions/frida-kahlo.jpg" },
      { name: "Chapultepec Castle", description: "Hilltop castle with city views and history museum", imageUrl: "/attractions/chapultepec.jpg" },
    ],
  },
  petra: {
    slug: "petra",
    name: "Petra",
    country: "Jordan",
    countryCode: "JO",
    description:
      "The Rose City carved into sandstone cliffs by the Nabataeans over 2,000 years ago. Petra is one of the New Seven Wonders of the World and a bucket-list archaeological marvel.",
    bestMonths: ["March", "April", "May", "October", "November"],
    averageTemp: { high: 23, low: 10 },
    highlights: ["The Treasury", "The Siq", "Monastery", "Royal Tombs", "Petra by Night"],
    imageUrl: "/destinations/petra.jpg",
    rating: 4.8,
    timezone: "Asia/Amman",
    favoriteFood: { name: "Mansaf", description: "Jordan's national dish of lamb cooked in fermented yogurt sauce served over rice" },
    attractions: [
      { name: "The Treasury (Al-Khazneh)", description: "Iconic rose-red facade carved into the cliff", imageUrl: "/attractions/treasury.jpg" },
      { name: "The Siq", description: "Dramatic narrow gorge entrance to the ancient city", imageUrl: "/attractions/siq.jpg" },
      { name: "The Monastery (Ad-Deir)", description: "Massive carved facade reached by 800 steps", imageUrl: "/attractions/monastery.jpg" },
    ],
  },
  dublin: {
    slug: "dublin",
    name: "Dublin",
    country: "Ireland",
    countryCode: "IE",
    description:
      "A literary city of Georgian architecture, lively pubs, and warm-hearted locals. Dublin brims with history from Viking origins to its role in modern Irish independence.",
    bestMonths: ["May", "June", "July", "August", "September"],
    averageTemp: { high: 16, low: 8 },
    highlights: ["Temple Bar", "Trinity College", "Guinness Storehouse", "St. Patrick's Cathedral", "Phoenix Park"],
    imageUrl: "/destinations/dublin.jpg",
    rating: 4.5,
    timezone: "Europe/Dublin",
    favoriteFood: { name: "Irish Stew", description: "Hearty slow-cooked stew of lamb, potatoes, carrots, and onions with fresh parsley" },
    attractions: [
      { name: "Trinity College & Book of Kells", description: "Historic university housing a medieval illuminated manuscript", imageUrl: "/attractions/trinity.jpg" },
      { name: "Guinness Storehouse", description: "Seven-storey brewery experience with rooftop bar", imageUrl: "/attractions/guinness.jpg" },
      { name: "Temple Bar", description: "Lively cultural quarter with pubs and street performers", imageUrl: "/attractions/temple-bar.jpg" },
    ],
  },
  seoul: {
    slug: "seoul",
    name: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    description:
      "A high-tech megacity where ancient palaces neighbor K-pop studios and sizzling barbecue joints. Seoul seamlessly merges 600 years of Joseon history with cutting-edge innovation.",
    bestMonths: ["April", "May", "September", "October"],
    averageTemp: { high: 21, low: 10 },
    highlights: ["Gyeongbokgung Palace", "Bukchon Hanok Village", "Myeongdong", "N Seoul Tower", "Hongdae"],
    imageUrl: "/destinations/seoul.jpg",
    rating: 4.6,
    timezone: "Asia/Seoul",
    favoriteFood: { name: "Korean BBQ", description: "Tabletop-grilled marinated beef bulgogi with banchan side dishes and ssamjang" },
    attractions: [
      { name: "Gyeongbokgung Palace", description: "Grandest of the five Joseon dynasty palaces", imageUrl: "/attractions/gyeongbokgung.jpg" },
      { name: "Bukchon Hanok Village", description: "Traditional Korean houses nestled between palaces", imageUrl: "/attractions/bukchon.jpg" },
      { name: "N Seoul Tower", description: "Landmark communication tower with city panoramas", imageUrl: "/attractions/n-seoul-tower.jpg" },
    ],
  },
  "siem reap": {
    slug: "siem-reap",
    name: "Siem Reap",
    country: "Cambodia",
    countryCode: "KH",
    description:
      "Gateway to the magnificent Angkor temple complex. Siem Reap combines awe-inspiring ancient ruins with a buzzing night market scene and warm Khmer hospitality.",
    bestMonths: ["November", "December", "January", "February", "March"],
    averageTemp: { high: 33, low: 24 },
    highlights: ["Angkor Wat", "Angkor Thom", "Ta Prohm", "Floating Villages", "Pub Street"],
    imageUrl: "/destinations/siemreap.jpg",
    rating: 4.7,
    timezone: "Asia/Phnom_Penh",
    favoriteFood: { name: "Fish Amok", description: "Creamy coconut fish curry steamed in banana leaves with kroeung spice paste" },
    attractions: [
      { name: "Angkor Wat", description: "World's largest religious monument and sunrise icon", imageUrl: "/attractions/angkor-wat.jpg" },
      { name: "Ta Prohm", description: "Jungle-enveloped temple famously used in Tomb Raider", imageUrl: "/attractions/ta-prohm.jpg" },
      { name: "Angkor Thom", description: "Walled city with the enigmatic Bayon temple faces", imageUrl: "/attractions/angkor-thom.jpg" },
    ],
  },
  florence: {
    slug: "florence",
    name: "Florence",
    country: "Italy",
    countryCode: "IT",
    description:
      "The birthplace of the Renaissance, Florence overflows with masterpieces by Michelangelo, Botticelli, and Brunelleschi. Tuscan cuisine and rolling hills complete the magic.",
    bestMonths: ["April", "May", "June", "September", "October"],
    averageTemp: { high: 24, low: 11 },
    highlights: ["Uffizi Gallery", "Duomo", "Ponte Vecchio", "Piazzale Michelangelo", "Tuscan Food Tours"],
    imageUrl: "/destinations/florence.jpg",
    rating: 4.8,
    timezone: "Europe/Rome",
    favoriteFood: { name: "Bistecca alla Fiorentina", description: "Thick-cut T-bone steak from Chianina cattle, grilled rare over hot coals" },
    attractions: [
      { name: "Uffizi Gallery", description: "Premier art museum with Botticelli's Birth of Venus", imageUrl: "/attractions/uffizi.jpg" },
      { name: "Florence Cathedral (Duomo)", description: "Iconic red-tiled dome by Brunelleschi", imageUrl: "/attractions/duomo-florence.jpg" },
      { name: "Ponte Vecchio", description: "Medieval stone bridge lined with jewellery shops", imageUrl: "/attractions/ponte-vecchio.jpg" },
    ],
  },
  jaipur: {
    slug: "jaipur",
    name: "Jaipur",
    country: "India",
    countryCode: "IN",
    description:
      "The Pink City, a regal Rajasthani capital of ornate palaces, majestic forts, and vibrant bazaars. Jaipur dazzles with its rich heritage, textiles, and spice-laden cuisine.",
    bestMonths: ["October", "November", "December", "January", "February", "March"],
    averageTemp: { high: 32, low: 18 },
    highlights: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar", "Bazaars"],
    imageUrl: "/destinations/jaipur.jpg",
    rating: 4.5,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Dal Baati Churma", description: "Rajasthani specialty of baked wheat balls with spiced lentils and sweet crushed wheat" },
    attractions: [
      { name: "Amber Fort", description: "Hilltop fortress with mirror-inlaid chambers", imageUrl: "/attractions/amber-fort.jpg" },
      { name: "Hawa Mahal", description: "Palace of Winds with its honeycomb facade", imageUrl: "/attractions/hawa-mahal.jpg" },
      { name: "City Palace", description: "Royal residence blending Mughal and Rajput architecture", imageUrl: "/attractions/city-palace.jpg" },
    ],
  },
  "vancouver": {
    slug: "vancouver",
    name: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    description:
      "A coastal gem where snow-capped mountains meet the Pacific Ocean. Vancouver offers world-class skiing, stunning parks, a thriving food scene, and multicultural neighborhoods.",
    bestMonths: ["June", "July", "August", "September"],
    averageTemp: { high: 19, low: 10 },
    highlights: ["Stanley Park", "Granville Island", "Capilano Bridge", "Grouse Mountain", "Gastown"],
    imageUrl: "/destinations/vancouver.jpg",
    rating: 4.6,
    timezone: "America/Vancouver",
    favoriteFood: { name: "Poutine", description: "Crispy fries smothered in rich gravy and topped with squeaky cheese curds" },
    attractions: [
      { name: "Stanley Park", description: "1,000-acre urban park with seawall and totem poles", imageUrl: "/attractions/stanley-park.jpg" },
      { name: "Capilano Suspension Bridge", description: "Swaying bridge 70m above a rainforest canyon", imageUrl: "/attractions/capilano.jpg" },
      { name: "Granville Island", description: "Vibrant peninsula with a public market and artisan shops", imageUrl: "/attractions/granville.jpg" },
    ],
  },
  zanzibar: {
    slug: "zanzibar",
    name: "Zanzibar",
    country: "Tanzania",
    countryCode: "TZ",
    description:
      "A tropical archipelago off East Africa known for spice plantations, turquoise waters, and the UNESCO-listed Stone Town. Zanzibar blends Swahili, Arab, and European influences.",
    bestMonths: ["June", "July", "August", "September", "January", "February"],
    averageTemp: { high: 31, low: 24 },
    highlights: ["Stone Town", "Nungwi Beach", "Spice Tours", "Prison Island", "Jozani Forest"],
    imageUrl: "/destinations/zanzibar.jpg",
    rating: 4.5,
    timezone: "Africa/Dar_es_Salaam",
    favoriteFood: { name: "Zanzibar Pizza", description: "Crispy street-food crepe filled with meat, egg, vegetables, and spices" },
    attractions: [
      { name: "Stone Town", description: "UNESCO labyrinth of narrow alleys and carved doors", imageUrl: "/attractions/stone-town.jpg" },
      { name: "Nungwi Beach", description: "Pristine white-sand beach on the northern tip", imageUrl: "/attractions/nungwi.jpg" },
      { name: "Jozani Forest", description: "Home to the rare red colobus monkey", imageUrl: "/attractions/jozani.jpg" },
    ],
  },
  edinburgh: {
    slug: "edinburgh",
    name: "Edinburgh",
    country: "United Kingdom",
    countryCode: "GB",
    description:
      "Scotland's dramatic capital of medieval castles, Georgian elegance, and a world-famous arts festival. Edinburgh's cobblestone streets inspired Harry Potter's magical world.",
    bestMonths: ["May", "June", "July", "August", "September"],
    averageTemp: { high: 15, low: 7 },
    highlights: ["Edinburgh Castle", "Royal Mile", "Arthur's Seat", "Fringe Festival", "Holyrood Palace"],
    imageUrl: "/destinations/edinburgh.jpg",
    rating: 4.6,
    timezone: "Europe/London",
    favoriteFood: { name: "Haggis", description: "Savory pudding of sheep's offal with oatmeal, onions, and spices in a casing" },
    attractions: [
      { name: "Edinburgh Castle", description: "Historic fortress dominating the city from Castle Rock", imageUrl: "/attractions/edinburgh-castle.jpg" },
      { name: "Arthur's Seat", description: "Ancient volcano offering panoramic city views", imageUrl: "/attractions/arthurs-seat.jpg" },
      { name: "Royal Mile", description: "Historic thoroughfare connecting Castle to Holyrood", imageUrl: "/attractions/royal-mile.jpg" },
    ],
  },
  cartagena: {
    slug: "cartagena",
    name: "Cartagena",
    country: "Colombia",
    countryCode: "CO",
    description:
      "A Caribbean jewel of colorful colonial architecture, cobblestone streets, and vibrant plazas. Cartagena's walled Old Town is a living museum of Spanish colonial heritage.",
    bestMonths: ["December", "January", "February", "March", "April"],
    averageTemp: { high: 32, low: 25 },
    highlights: ["Walled City", "Castillo San Felipe", "Rosario Islands", "Getsemaní", "Street Food"],
    imageUrl: "/destinations/cartagena.jpg",
    rating: 4.5,
    timezone: "America/Bogota",
    favoriteFood: { name: "Arepa de Huevo", description: "Deep-fried corn cake stuffed with a whole egg and seasoned ground beef" },
    attractions: [
      { name: "Walled City", description: "UNESCO-listed colonial center with colorful facades", imageUrl: "/attractions/walled-city.jpg" },
      { name: "Castillo San Felipe", description: "Massive Spanish fortress with underground tunnels", imageUrl: "/attractions/san-felipe.jpg" },
      { name: "Rosario Islands", description: "Archipelago of coral islands with turquoise waters", imageUrl: "/attractions/rosario.jpg" },
    ],
  },
  "chiang mai": {
    slug: "chiang-mai",
    name: "Chiang Mai",
    country: "Thailand",
    countryCode: "TH",
    description:
      "The Rose of the North, a laid-back city surrounded by misty mountains and hundreds of Buddhist temples. Chiang Mai is a haven for foodies, digital nomads, and adventurers.",
    bestMonths: ["November", "December", "January", "February"],
    averageTemp: { high: 32, low: 20 },
    highlights: ["Doi Suthep Temple", "Night Bazaar", "Elephant Sanctuaries", "Old City Temples", "Cooking Classes"],
    imageUrl: "/destinations/chiangmai.jpg",
    rating: 4.6,
    timezone: "Asia/Bangkok",
    favoriteFood: { name: "Khao Soi", description: "Northern Thai coconut curry noodle soup topped with crispy fried noodles" },
    attractions: [
      { name: "Doi Suthep", description: "Sacred hilltop temple with sweeping city views", imageUrl: "/attractions/doi-suthep.jpg" },
      { name: "Night Bazaar", description: "Sprawling evening market with crafts and street food", imageUrl: "/attractions/night-bazaar.jpg" },
      { name: "Elephant Nature Park", description: "Ethical elephant rescue and rehabilitation center", imageUrl: "/attractions/elephant-park.jpg" },
    ],
  },
  berlin: {
    slug: "berlin",
    name: "Berlin",
    country: "Germany",
    countryCode: "DE",
    description:
      "A creative, edgy capital defined by its turbulent history and thriving arts scene. Berlin captivates with world-class museums, legendary nightlife, and vibrant street art.",
    bestMonths: ["May", "June", "July", "August", "September"],
    averageTemp: { high: 20, low: 9 },
    highlights: ["Brandenburg Gate", "Berlin Wall Memorial", "Museum Island", "Reichstag", "East Side Gallery"],
    imageUrl: "/destinations/berlin.jpg",
    rating: 4.5,
    timezone: "Europe/Berlin",
    favoriteFood: { name: "Currywurst", description: "Sliced pork sausage smothered in curry ketchup, served with fries or a bread roll" },
    attractions: [
      { name: "Brandenburg Gate", description: "Iconic 18th-century neoclassical monument", imageUrl: "/attractions/brandenburg.jpg" },
      { name: "Museum Island", description: "UNESCO island complex of five world-class museums", imageUrl: "/attractions/museum-island.jpg" },
      { name: "East Side Gallery", description: "Longest surviving section of the Berlin Wall with murals", imageUrl: "/attractions/east-side.jpg" },
    ],
  },
  "new zealand": {
    slug: "queenstown",
    name: "Queenstown",
    country: "New Zealand",
    countryCode: "NZ",
    description:
      "The adventure capital of the world, set on the shores of crystal-clear Lake Wakatipu surrounded by the Remarkables mountain range. A paradise for thrill-seekers and nature lovers.",
    bestMonths: ["December", "January", "February", "March"],
    averageTemp: { high: 22, low: 8 },
    highlights: ["Bungee Jumping", "Milford Sound", "Remarkables Ski Area", "Lake Wakatipu", "Skyline Gondola"],
    imageUrl: "/destinations/queenstown.jpg",
    rating: 4.8,
    timezone: "Pacific/Auckland",
    favoriteFood: { name: "Fergburger", description: "Legendary oversized gourmet burger from Queenstown's iconic burger joint" },
    attractions: [
      { name: "Milford Sound", description: "Majestic fjord with cascading waterfalls and dolphins", imageUrl: "/attractions/milford-sound.jpg" },
      { name: "AJ Hackett Bungy", description: "World's first commercial bungee jumping site", imageUrl: "/attractions/bungy.jpg" },
      { name: "Skyline Gondola", description: "Scenic cable car with luge rides and stargazing", imageUrl: "/attractions/skyline.jpg" },
    ],
  },
  havana: {
    slug: "havana",
    name: "Havana",
    country: "Cuba",
    countryCode: "CU",
    description:
      "A time-capsule city of pastel Art Deco buildings, vintage American cars, and irresistible salsa rhythms. Havana pulses with revolutionary history and Caribbean soul.",
    bestMonths: ["November", "December", "January", "February", "March", "April"],
    averageTemp: { high: 30, low: 22 },
    highlights: ["Old Havana", "Malecón", "Revolution Square", "Vintage Cars", "Tropicana"],
    imageUrl: "/destinations/havana.jpg",
    rating: 4.4,
    timezone: "America/Havana",
    favoriteFood: { name: "Ropa Vieja", description: "Shredded beef braised in tomato sauce with peppers and onions, served with rice and beans" },
    attractions: [
      { name: "Old Havana (Habana Vieja)", description: "UNESCO World Heritage colonial district", imageUrl: "/attractions/old-havana.jpg" },
      { name: "Malecón", description: "Iconic seaside promenade stretching 8 km along the coast", imageUrl: "/attractions/malecon.jpg" },
      { name: "El Capitolio", description: "Grand neoclassical building resembling the US Capitol", imageUrl: "/attractions/capitolio.jpg" },
    ],
  },
  dubrovnik: {
    slug: "dubrovnik",
    name: "Dubrovnik",
    country: "Croatia",
    countryCode: "HR",
    description:
      "The Pearl of the Adriatic, a walled medieval city of terracotta rooftops and sparkling blue sea. Dubrovnik gained new fame as a Game of Thrones filming location.",
    bestMonths: ["May", "June", "September", "October"],
    averageTemp: { high: 25, low: 15 },
    highlights: ["City Walls Walk", "Old Town", "Lokrum Island", "Cable Car", "Game of Thrones Tour"],
    imageUrl: "/destinations/dubrovnik.jpg",
    rating: 4.7,
    timezone: "Europe/Zagreb",
    favoriteFood: { name: "Black Risotto", description: "Creamy risotto made with cuttlefish ink, giving it a striking dark color and briny flavor" },
    attractions: [
      { name: "City Walls", description: "1,940m of medieval fortifications with sea views", imageUrl: "/attractions/city-walls.jpg" },
      { name: "Stradun", description: "Limestone-paved main street through the Old Town", imageUrl: "/attractions/stradun.jpg" },
      { name: "Lokrum Island", description: "Forested island with a botanical garden and peacocks", imageUrl: "/attractions/lokrum.jpg" },
    ],
  },
  "lake como": {
    slug: "lake-como",
    name: "Lake Como",
    country: "Italy",
    countryCode: "IT",
    description:
      "A jewel of the Italian Lakes, framed by snow-dusted Alps and dotted with pastel villas and lush gardens. Lake Como has enchanted artists and aristocrats for centuries.",
    bestMonths: ["May", "June", "July", "August", "September"],
    averageTemp: { high: 26, low: 14 },
    highlights: ["Villa del Balbianello", "Bellagio", "Como Cathedral", "Ferry Rides", "Lakeside Dining"],
    imageUrl: "/destinations/lakecomo.jpg",
    rating: 4.7,
    timezone: "Europe/Rome",
    favoriteFood: { name: "Pizzoccheri", description: "Hearty buckwheat pasta with melted cheese, potatoes, and savoy cabbage from Lombardy" },
    attractions: [
      { name: "Villa del Balbianello", description: "Elegant lakeside villa featured in Star Wars and Bond", imageUrl: "/attractions/balbianello.jpg" },
      { name: "Bellagio", description: "Picturesque village known as the Pearl of the Lake", imageUrl: "/attractions/bellagio.jpg" },
      { name: "Como Cathedral", description: "Gothic-Renaissance cathedral near the lake shore", imageUrl: "/attractions/como-cathedral.jpg" },
    ],
  },
  kathmandu: {
    slug: "kathmandu",
    name: "Kathmandu",
    country: "Nepal",
    countryCode: "NP",
    description:
      "A chaotic, colorful gateway to the Himalayas. Kathmandu's ancient temple squares, prayer flags, and mountain panoramas create an unforgettable spiritual and adventure hub.",
    bestMonths: ["March", "April", "May", "October", "November"],
    averageTemp: { high: 24, low: 10 },
    highlights: ["Swayambhunath", "Durbar Square", "Boudhanath", "Thamel", "Everest Flights"],
    imageUrl: "/destinations/kathmandu.jpg",
    rating: 4.4,
    timezone: "Asia/Kathmandu",
    favoriteFood: { name: "Momo", description: "Steamed Nepali dumplings filled with spiced meat or vegetables, served with tomato chutney" },
    attractions: [
      { name: "Swayambhunath (Monkey Temple)", description: "Ancient hilltop stupa with panoramic valley views", imageUrl: "/attractions/swayambhunath.jpg" },
      { name: "Boudhanath Stupa", description: "One of the largest spherical stupas in the world", imageUrl: "/attractions/boudhanath.jpg" },
      { name: "Pashupatinath Temple", description: "Sacred Hindu temple on the Bagmati River", imageUrl: "/attractions/pashupatinath.jpg" },
    ],
  },
  mumbai: {
    slug: "mumbai",
    name: "Mumbai",
    country: "India",
    countryCode: "IN",
    description:
      "India's city of dreams, where Bollywood glamour meets colonial-era architecture and bustling street markets. Mumbai pulses with relentless energy, incredible street food, and the spirit of enterprise.",
    bestMonths: ["October", "November", "December", "January", "February"],
    averageTemp: { high: 33, low: 24 },
    highlights: ["Gateway of India", "Marine Drive", "Elephanta Caves", "Dhobi Ghat", "Chhatrapati Shivaji Terminus"],
    imageUrl: "/destinations/mumbai.jpg",
    rating: 4.4,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Vada Pav", description: "Mumbai's iconic spicy potato fritter sandwiched in a soft bun with chutneys" },
    attractions: [
      { name: "Gateway of India", description: "Iconic arch monument overlooking the Arabian Sea", imageUrl: "/attractions/gateway-india.jpg" },
      { name: "Chhatrapati Shivaji Terminus", description: "UNESCO-listed Victorian Gothic railway station", imageUrl: "/attractions/cst.jpg" },
      { name: "Elephanta Caves", description: "Ancient rock-cut cave temples on a harbour island", imageUrl: "/attractions/elephanta.jpg" },
    ],
  },
  delhi: {
    slug: "delhi",
    name: "Delhi",
    country: "India",
    countryCode: "IN",
    description:
      "India's sprawling capital where Mughal grandeur meets modern ambition. Delhi layers centuries of history from ancient tombs to the grand boulevards of New Delhi.",
    bestMonths: ["October", "November", "February", "March"],
    averageTemp: { high: 34, low: 16 },
    highlights: ["Red Fort", "Qutub Minar", "India Gate", "Chandni Chowk", "Humayun's Tomb"],
    imageUrl: "/destinations/delhi.jpg",
    rating: 4.3,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Chole Bhature", description: "Spicy chickpea curry served with puffy deep-fried bread, a beloved Delhi breakfast" },
    attractions: [
      { name: "Red Fort", description: "Majestic Mughal fortress and UNESCO World Heritage Site", imageUrl: "/attractions/red-fort.jpg" },
      { name: "Humayun's Tomb", description: "Stunning Mughal garden tomb that inspired the Taj Mahal", imageUrl: "/attractions/humayuns-tomb.jpg" },
      { name: "Qutub Minar", description: "73-metre tall victory tower dating to the 12th century", imageUrl: "/attractions/qutub-minar.jpg" },
    ],
  },
  goa: {
    slug: "goa",
    name: "Goa",
    country: "India",
    countryCode: "IN",
    description:
      "India's beach paradise blending Portuguese colonial heritage with tropical vibes. Goa enchants with golden shores, vibrant nightlife, spice plantations, and whitewashed churches.",
    bestMonths: ["November", "December", "January", "February", "March"],
    averageTemp: { high: 33, low: 23 },
    highlights: ["Baga Beach", "Basilica of Bom Jesus", "Dudhsagar Falls", "Spice Plantations", "Anjuna Flea Market"],
    imageUrl: "/destinations/goa.jpg",
    rating: 4.5,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Fish Curry Rice", description: "Tangy coconut-based fish curry with steamed rice, the quintessential Goan meal" },
    attractions: [
      { name: "Basilica of Bom Jesus", description: "UNESCO-listed 16th-century church housing St. Francis Xavier's relics", imageUrl: "/attractions/bom-jesus.jpg" },
      { name: "Dudhsagar Falls", description: "Spectacular four-tiered waterfall in the Western Ghats", imageUrl: "/attractions/dudhsagar.jpg" },
      { name: "Fort Aguada", description: "17th-century Portuguese fort overlooking the Arabian Sea", imageUrl: "/attractions/fort-aguada.jpg" },
    ],
  },
  varanasi: {
    slug: "varanasi",
    name: "Varanasi",
    country: "India",
    countryCode: "IN",
    description:
      "One of the world's oldest continuously inhabited cities, Varanasi is the spiritual heart of Hinduism. Ancient ghats descend to the sacred Ganges, where life, death, and devotion intertwine.",
    bestMonths: ["October", "November", "February", "March"],
    averageTemp: { high: 33, low: 16 },
    highlights: ["Dashashwamedh Ghat", "Ganga Aarti", "Kashi Vishwanath Temple", "Sarnath", "Boat Ride at Dawn"],
    imageUrl: "/destinations/varanasi.jpg",
    rating: 4.5,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Kachori Sabzi", description: "Crispy fried pastry filled with spiced lentils, served with tangy potato curry" },
    attractions: [
      { name: "Dashashwamedh Ghat", description: "Main ghat famous for its spectacular evening Ganga Aarti", imageUrl: "/attractions/dashashwamedh.jpg" },
      { name: "Sarnath", description: "Sacred Buddhist site where Buddha gave his first sermon", imageUrl: "/attractions/sarnath.jpg" },
      { name: "Kashi Vishwanath Temple", description: "One of Hinduism's most sacred Shiva temples", imageUrl: "/attractions/kashi-vishwanath.jpg" },
    ],
  },
  udaipur: {
    slug: "udaipur",
    name: "Udaipur",
    country: "India",
    countryCode: "IN",
    description:
      "The City of Lakes, a romantic Rajasthani gem of shimmering palaces reflected in tranquil waters. Udaipur enchants with its regal heritage, intricate havelis, and sunset boat rides.",
    bestMonths: ["October", "November", "December", "January", "February", "March"],
    averageTemp: { high: 33, low: 16 },
    highlights: ["City Palace", "Lake Pichola", "Jag Mandir", "Saheliyon ki Bari", "Monsoon Palace"],
    imageUrl: "/destinations/udaipur.jpg",
    rating: 4.7,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Dal Baati Churma", description: "Baked wheat dough balls dipped in ghee, served with spiced lentils and sweet crushed wheat" },
    attractions: [
      { name: "City Palace", description: "Sprawling lakeside palace complex with museums and courtyards", imageUrl: "/attractions/udaipur-city-palace.jpg" },
      { name: "Lake Pichola", description: "Serene artificial lake with island palaces", imageUrl: "/attractions/lake-pichola.jpg" },
      { name: "Jag Mandir", description: "Island palace with gardens and marble elephants", imageUrl: "/attractions/jag-mandir.jpg" },
    ],
  },
  agra: {
    slug: "agra",
    name: "Agra",
    country: "India",
    countryCode: "IN",
    description:
      "Home to the Taj Mahal, one of the world's most iconic monuments. Agra's Mughal heritage shines through its magnificent forts, tombs, and the unparalleled beauty of white marble at sunrise.",
    bestMonths: ["October", "November", "February", "March"],
    averageTemp: { high: 34, low: 14 },
    highlights: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh", "Itimad-ud-Daulah"],
    imageUrl: "/destinations/agra.jpg",
    rating: 4.7,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Petha", description: "Translucent sweet made from ash gourd, a beloved Agra delicacy in many flavors" },
    attractions: [
      { name: "Taj Mahal", description: "Ivory-white marble mausoleum and symbol of eternal love", imageUrl: "/attractions/taj-mahal.jpg" },
      { name: "Agra Fort", description: "Massive red sandstone UNESCO fortress with palatial chambers", imageUrl: "/attractions/agra-fort.jpg" },
      { name: "Fatehpur Sikri", description: "Abandoned Mughal city with stunning red sandstone architecture", imageUrl: "/attractions/fatehpur-sikri.jpg" },
    ],
  },
  kerala: {
    slug: "kerala",
    name: "Kerala",
    country: "India",
    countryCode: "IN",
    description:
      "God's Own Country, a lush tropical paradise of palm-fringed backwaters, misty hill stations, and Ayurvedic wellness retreats. Kerala offers serene houseboat cruises and vibrant Kathakali performances.",
    bestMonths: ["September", "October", "November", "December", "January", "February", "March"],
    averageTemp: { high: 32, low: 23 },
    highlights: ["Backwater Houseboats", "Munnar Tea Gardens", "Fort Kochi", "Periyar Wildlife", "Kovalam Beach"],
    imageUrl: "/destinations/kerala.jpg",
    rating: 4.7,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Appam with Stew", description: "Lacy rice pancake with a soft center, served with fragrant coconut vegetable stew" },
    attractions: [
      { name: "Alleppey Backwaters", description: "Tranquil network of lagoons, lakes, and canals", imageUrl: "/attractions/alleppey.jpg" },
      { name: "Munnar", description: "Hill station blanketed in rolling tea plantations", imageUrl: "/attractions/munnar.jpg" },
      { name: "Fort Kochi", description: "Historic quarter with Chinese fishing nets and colonial architecture", imageUrl: "/attractions/fort-kochi.jpg" },
    ],
  },
  kolkata: {
    slug: "kolkata",
    name: "Kolkata",
    country: "India",
    countryCode: "IN",
    description:
      "The cultural capital of India, Kolkata brims with literary heritage, colonial architecture, and artistic passion. From Durga Puja festivities to iconic trams and sweet shops, the city has soul.",
    bestMonths: ["October", "November", "December", "February", "March"],
    averageTemp: { high: 33, low: 18 },
    highlights: ["Victoria Memorial", "Howrah Bridge", "Durga Puja", "College Street", "Kumartuli"],
    imageUrl: "/destinations/kolkata.jpg",
    rating: 4.4,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Rosogolla", description: "Spongy cottage cheese balls soaked in light sugar syrup, Bengal's most famous sweet" },
    attractions: [
      { name: "Victoria Memorial", description: "Grand white marble museum dedicated to Queen Victoria", imageUrl: "/attractions/victoria-memorial.jpg" },
      { name: "Howrah Bridge", description: "Iconic cantilever bridge spanning the Hooghly River", imageUrl: "/attractions/howrah-bridge.jpg" },
      { name: "Dakshineswar Kali Temple", description: "Sacred Hindu temple on the banks of the Hooghly", imageUrl: "/attractions/dakshineswar.jpg" },
    ],
  },
  amritsar: {
    slug: "amritsar",
    name: "Amritsar",
    country: "India",
    countryCode: "IN",
    description:
      "The spiritual center of Sikhism, home to the breathtaking Golden Temple. Amritsar blends deep devotion with Punjabi exuberance, legendary food, and the moving Wagah Border ceremony.",
    bestMonths: ["October", "November", "February", "March"],
    averageTemp: { high: 34, low: 12 },
    highlights: ["Golden Temple", "Wagah Border Ceremony", "Jallianwala Bagh", "Partition Museum", "Punjabi Street Food"],
    imageUrl: "/destinations/amritsar.jpg",
    rating: 4.6,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Amritsari Kulcha", description: "Stuffed tandoor-baked flatbread with spiced potato filling, served with chole and lassi" },
    attractions: [
      { name: "Golden Temple", description: "Holiest Sikh gurdwara with a stunning gold-plated sanctum", imageUrl: "/attractions/golden-temple.jpg" },
      { name: "Jallianwala Bagh", description: "Memorial garden honoring the 1919 massacre victims", imageUrl: "/attractions/jallianwala-bagh.jpg" },
      { name: "Wagah Border", description: "Dramatic flag-lowering ceremony at the India-Pakistan border", imageUrl: "/attractions/wagah.jpg" },
    ],
  },
  rishikesh: {
    slug: "rishikesh",
    name: "Rishikesh",
    country: "India",
    countryCode: "IN",
    description:
      "The Yoga Capital of the World, nestled in the Himalayan foothills along the sacred Ganges. Rishikesh draws seekers and adventurers alike with ashrams, white-water rafting, and Beatles history.",
    bestMonths: ["September", "October", "November", "March", "April", "May"],
    averageTemp: { high: 30, low: 14 },
    highlights: ["Lakshman Jhula", "Beatles Ashram", "River Rafting", "Triveni Ghat Aarti", "Yoga & Meditation"],
    imageUrl: "/destinations/rishikesh.jpg",
    rating: 4.5,
    timezone: "Asia/Kolkata",
    favoriteFood: { name: "Aloo Puri", description: "Puffy deep-fried bread with spiced potato curry, a popular North Indian breakfast" },
    attractions: [
      { name: "Lakshman Jhula", description: "Iconic iron suspension bridge over the Ganges", imageUrl: "/attractions/lakshman-jhula.jpg" },
      { name: "Beatles Ashram", description: "Abandoned ashram where the Beatles studied meditation in 1968", imageUrl: "/attractions/beatles-ashram.jpg" },
      { name: "Triveni Ghat", description: "Sacred bathing ghat with evening aarti ceremony", imageUrl: "/attractions/triveni-ghat.jpg" },
    ],
  },
};

const airlines = [
  "Delta Air Lines",
  "JetBlue Airways",
  "United Airlines",
  "American Airlines",
  "Emirates",
  "British Airways",
  "Lufthansa",
  "Air France",
  "Japan Airlines",
  "Singapore Airlines",
  "Qatar Airways",
  "Turkish Airlines",
];

const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export function searchDestination(query: string): Destination | null {
  const key = query.toLowerCase().trim();
  // Direct match
  if (destinations[key]) return destinations[key];
  // Partial match
  for (const [k, v] of Object.entries(destinations)) {
    if (k.includes(key) || v.name.toLowerCase().includes(key) || v.country.toLowerCase().includes(key)) {
      return v;
    }
  }
  return null;
}

export function getAllDestinations(): Destination[] {
  return Object.values(destinations);
}

export function getBestTimeToVisit(destination: Destination): string {
  const best = destination.bestMonths;
  if (best.length <= 2) return best.join(" and ");
  return `${best.slice(0, -1).join(", ")}, and ${best[best.length - 1]}`;
}

export function getCurrentSeason(destination: Destination): string {
  const currentMonth = months[new Date().getMonth()];
  if (destination.bestMonths.includes(currentMonth)) {
    return "peak";
  }
  // Check if within one month of peak
  const currentIdx = new Date().getMonth();
  for (const m of destination.bestMonths) {
    const mIdx = months.indexOf(m);
    if (Math.abs(currentIdx - mIdx) <= 1 || Math.abs(currentIdx - mIdx) >= 11) {
      return "shoulder";
    }
  }
  return "off-peak";
}

export function getWeatherDescription(
  destination: Destination,
  season: string
): string {
  const { high, low } = destination.averageTemp;
  const seasonDescriptions: Record<string, string> = {
    peak: `Perfect weather with temperatures around ${high}°C (${Math.round(high * 1.8 + 32)}°F). Ideal conditions for sightseeing and outdoor activities.`,
    shoulder: `Pleasant weather with mild temperatures between ${low}°C and ${high}°C (${Math.round(low * 1.8 + 32)}°F–${Math.round(high * 1.8 + 32)}°F). Fewer crowds and good value.`,
    "off-peak": `Off-season temperatures around ${low}°C (${Math.round(low * 1.8 + 32)}°F). Budget-friendly with fewer tourists, but weather may be less ideal.`,
  };
  return seasonDescriptions[season] || seasonDescriptions["shoulder"];
}

const countryBasePrices: Record<string, number> = {
  France: 450,
  Japan: 850,
  Indonesia: 950,
  Spain: 500,
  USA: 180,
  "United Kingdom": 550,
  Italy: 520,
  UAE: 750,
  Australia: 1200,
  Peru: 600,
  Greece: 620,
  Maldives: 1100,
  Netherlands: 480,
  Thailand: 900,
  "South Africa": 1050,
  Morocco: 550,
  "Czech Republic": 470,
  Turkey: 580,
  Brazil: 700,
  Singapore: 950,
  Argentina: 800,
  Portugal: 460,
  Austria: 490,
  China: 900,
  Egypt: 650,
  Iceland: 550,
  Malaysia: 920,
  Vietnam: 880,
  Mexico: 350,
  Jordan: 700,
  Ireland: 500,
  "South Korea": 870,
  Cambodia: 950,
  Germany: 460,
  "New Zealand": 1300,
  Cuba: 400,
  Croatia: 540,
  Nepal: 950,
  Colombia: 450,
  Tanzania: 1000,
  Canada: 250,
};

export function generateFlights(destination: Destination): FlightOption[] {
  const price = countryBasePrices[destination.country] || 600;
  const numFlights = 4 + Math.floor(Math.random() * 3);
  const flights: FlightOption[] = [];

  for (let i = 0; i < numFlights; i++) {
    const airline = airlines[Math.floor(Math.random() * airlines.length)];
    const stops = Math.random() > 0.4 ? (Math.random() > 0.5 ? 2 : 1) : 0;
    const baseHours = stops === 0 ? 6 + Math.random() * 10 : 10 + Math.random() * 14;
    const hours = Math.floor(baseHours);
    const minutes = Math.floor(Math.random() * 60);
    const departHour = 5 + Math.floor(Math.random() * 16);
    const departMin = Math.floor(Math.random() * 60);
    const arriveHour = (departHour + hours) % 24;
    const arriveMin = (departMin + minutes) % 60;
    const variation = 0.7 + Math.random() * 0.8;
    const finalPrice = Math.round(price * variation * (stops === 0 ? 1.3 : stops === 1 ? 1 : 0.85));

    flights.push({
      airline,
      departure: "Boston (BOS)",
      arrival: `${destination.name} (${destination.name.substring(0, 3).toUpperCase()})`,
      duration: `${hours}h ${minutes}m`,
      stops,
      price: finalPrice,
      departureTime: `${departHour.toString().padStart(2, "0")}:${departMin.toString().padStart(2, "0")}`,
      arrivalTime: `${arriveHour.toString().padStart(2, "0")}:${arriveMin.toString().padStart(2, "0")}`,
    });
  }

  return flights.sort((a, b) => a.price - b.price);
}

export function getMonthlyRecommendations(month?: string) {
  const targetMonth = month || months[new Date().getMonth()];
  const allDests = Object.values(destinations);
  const recommended = allDests.filter((d) =>
    d.bestMonths.includes(targetMonth)
  );
  return {
    month: targetMonth,
    destinations: recommended.length > 0 ? recommended : allDests.slice(0, 4),
  };
}
